### PR TITLE
Update ec_si.py template

### PR DESCRIPTION
**Pull request by DanielNwaeze**
Removed determination datetime column and added EC_nuts3 in columns list with description

### CODE REVIEW

**Review by m-mohr — CHANGES_REQUESTED** [review]
There are many unrelated changes in the PR that override recent commits. Please clean this up.

**Comment by DanielNwaeze** [comment]
@m-mohr There seems to be a lot of changes you've made in the Fiboa repo and now, running fiboa convert is broken. Did we really need to make these modifications?

**Comment by DanielNwaeze** [comment]
No worries. It was a dependency issue as I can see the cli version was updated

**Comment by m-mohr** [comment]
Yes, we needed the changes, you just would have needed to work on the latest version. Why did you not `git pull` before you applied further updates? @DanielNwaeze

**Comment by DanielNwaeze** [comment]
I had no idea the version got updated on Git. it was the same as at Thursday when I pulled it. Logged on yesterday with the assumption it was still the same. Oversight on my part

**Pull request closed without merging**
