### PR TITLE
eurocrops latvia

### PR DESCRIPTION
**Pull request by eddiechoi00**

### CODE REVIEW

**Comment by m-mohr** [comment]
43 changed files? Somethings wrong here... 🤔

**Comment by eddiechoi00** [comment]
@m-mohr Yea, I'm really not sure what happened here – I cloned the repository, checked out a new branch, added the necessary files, committed then pushed it, but it seems to think I've changed every single file like it was an empty repository before...

**Comment by m-mohr** [comment]
They are all in a separate folder though, build. I think you could simply remove it?

**Comment by eddiechoi00** [comment]
My apologies, I didn't notice they were in a separate folder. I think they were created when I was committing.

**Comment by eddiechoi00** [comment]
@m-mohr I've deleted the files.

**Comment by m-mohr** [comment]
Great. Looks good. What's up with PRODUCT_DE?

**Comment by m-mohr** [comment]
Has it exactly the same values? If yes, you can likely leave it out, indeed.

**Comment by eddiechoi00** [comment]
They seem to be exactly same except for 1 value of 432188 values.
The said difference exists where one value of `PRODUCT_DE` for all values of `ec:translated_name` equals to **'Meadow fescue for seed production'** is listed as **'P?avas skarene, s?klas ieguvei'** instead of **'P?avas auzene, s?klas ieguvei'**. Considering the encoding issues of `PRODUCT_DE`, I think it would be better to leave it out despite this issue. What do you think?

**Pull request merged**
